### ISSUE TITLE
Down usage column missing

### ISSUE THREAD

**Issue by rokcarl** [simejanko/siol-bandwidth-meter#1]
I ran this and got this traceback:

    Traceback (most recent call last):
      File "bandwidth_meter.py", line 86, in <module>
        port_stats = get_stats(args.ip, args.delay)
      File "bandwidth_meter.py", line 70, in get_stats
        avg_down_usage = (int(port_data[DOWN_USAGE_COLUMN]) / 1e3) / delay
    IndexError: list index out of range

I checked what was going on, so `DOWN_USAGE_COLUMN` is `9`, but the `port_data` only has 9 items: `['eth0', '46041', '187', '0', '0', '40279', '169', '0', '0']`.

**Comment by simejanko** [comment]
Would you mind telling me if  your device is InnBox v45? `port_data` might be different on other devices. In case your device is InnBox v45, software version on it might be different, which would be troublesome. Going to http://192.168.1.1 and loging-in, you should be able to see software version at the top (Device info). What is it?

**Comment by rokcarl** [comment]
Duh, sorry, you're right, I'm on the V60U.

**Comment by simejanko** [comment]
The fact that you got as far as retrieving`port_data` might mean that supporting your device is relatively trivial. Judging from the data you get, it wasn't hard to guess what each column means. If my assumptions were correct, your device should now be supported, since the number of LAN ports seems to match to that of v45. I would appreciate if you could test that out by perfroming some sanity tests by uploading/dowloading something and seeing if the changes are reflected in the monitor.

**Comment by rokcarl** [comment]
I ran it again and now it's working, thanks.
